spring:
  application:
    name: nova-config-server
    group: infra
  profiles:
    active: local # 기본 프로필
    group:
      default: ["local"]
      local: ["local"]
      dev: ["dev"]
      prod: ["prod"]
      docker: ["docker"]