spring:
  application:
    name: nova-config-server
    group: infra
  profiles:
    group:
      default:
        - local
      local:
        - local
      dev:
        - dev
      prod:
        - prod